<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Qualification Standards Configuration
    |--------------------------------------------------------------------------
    | Complete list for Kindergarten, Elementary, Junior High School,
    | and Senior High School positions.
    |--------------------------------------------------------------------------
    */

    // ==========================================================
    // KINDERGARTEN (same as Elementary)
    // ==========================================================
    'kindergarten' => [
        'Teacher I' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => 'None Required',
            'training_hours' => 0,
            'experience'  => 'None Required',
            'experience_years' => 0,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher II' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 8,
            'experience'  => '1 year of teaching experience',
            'experience_years' => 1,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher III' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 16,
            'experience'  => '2 years of teaching experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher IV' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 16,
            'experience'  => '3 years of teaching experience',
            'experience_years' => 3,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher V' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '3 years of teaching experience',
            'experience_years' => 3,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher VI' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 years of teaching experience',
            'experience_years' => 4,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher VII' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 years of teaching experience',
            'experience_years' => 4,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher I' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher II' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 1 year relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher III' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 2 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher IV' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 3 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher V' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 16 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 4 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
    ],

    // ==========================================================
    // ELEMENTARY
    // ==========================================================
    'elementary' => [
        'Teacher I' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => 'None Required',
            'training_hours' => 0,
            'experience'  => 'None Required',
            'experience_years' => 0,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher II' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 8,
            'experience'  => '1 year of teaching experience',
            'experience_years' => 1,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher III' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 16,
            'experience'  => '2 years of teaching experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher IV' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 16,
            'experience'  => '3 years of teaching experience',
            'experience_years' => 3,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher V' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '3 years of teaching experience',
            'experience_years' => 3,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher VI' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 years of teaching experience',
            'experience_years' => 4,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher VII' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 years of teaching experience',
            'experience_years' => 4,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher I' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher II' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 1 year relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher III' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 2 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher IV' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 3 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher V' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 16 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 4 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
    ],

    // ==========================================================
    // JUNIOR HIGH SCHOOL (from Excel)
    // ==========================================================
    'junior_high' => [
        'Teacher I' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => 'None required',
            'training_hours' => 0,
            'experience'  => 'None required',
            'experience_years' => 0,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher II' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of training in any of or a cumulative of the following: Curriculum, Pedagogy, Subject Specialization acquired within the last 5 years',
            'training_hours' => 8,
            'experience'  => '1 year teaching experience',
            'experience_years' => 1,
            'eligibility' => 'RA 1080, as amended (Teacher-Secondary)',
        ],
        'Teacher III' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training',
            'training_hours' => 8,
            'experience'  => '2 years relevant experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher IV' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training',
            'training_hours' => 8,
            'experience'  => '2 years relevant experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Teacher V' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training',
            'training_hours' => 8,
            'experience'  => '2 years relevant experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
         'Teacher VI' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training',
            'training_hours' => 8,
            'experience'  => '2 years relevant experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
         'Teacher VII' => [
            'education'   => 'Bachelor’s Degree in Education or Bachelor’s Degree in relevant subject or learning area with at least 18 professional units in Education',
            'training'    => '8 hours of relevant training',
            'training_hours' => 8,
            'experience'  => '2 years relevant experience',
            'experience_years' => 2,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher I' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher II' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 1 year relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher III' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 2 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher IV' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 3 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
        'Master Teacher V' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 16 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 4 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'RA 1080 (Teacher)',
        ],
    ],

    // ==========================================================
    // SENIOR HIGH SCHOOL (from Excel)
    // ==========================================================
    'senior_high' => [
        'Teacher I' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 15 units of specialization in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 15 units of specialization in the relevant strand /subject',
            'training'    => 'None required',
            'training_hours' => 0,
            'experience'  => 'None required',
            'experience_years' => 0,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher II' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 6 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 6 units towards Master’s degree in the relevant strand /subject',
            'training'    => '8 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 8,
            'experience'  => '1 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 1,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher III' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 12 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 12 units towards Master’s degree in the relevant strand /subject',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years',
            'training_hours' => 16,
            'experience'  => '2 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 2,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher IV' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 18 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 18 units towards Master’s degree in the relevant strand /subject',
            'training'    => '16 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 16,
            'experience'  => '3 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 3,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher V' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 24 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 24 units towards Master’s degree in the relevant strand /subject',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '3 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 3,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher VI' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 30 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 30 units towards Master’s degree in the relevant strand /subject',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 4,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Teacher VII' => [
            'education'   => 'Bachelor’s Degree with a major in the relevant strand/subject plus 18 professional units in Education; or any Bachelor’s Degree with at least 36 units towards Master’s Degree in the relevant strand/subject plus 18 professional units in Education/Bachelor’s Degree with a major in the relevant strand/subject; or any Bachelor’s degree with at least 36 units towards Master’s degree in the relevant strand /subject',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization acquired within 5 years OR Completion of NEAP-requisite professional development program for Career Stage II (Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '4 year of teaching experience or industry work in relevant strand/subject',
            'experience_years' => 4,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Master Teacher I' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience',
            'experience_years' => 5,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Master Teacher II' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Highly Proficient Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 1 year relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Master Teacher III' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage IV (Distinguished Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 2 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Master Teacher IV' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 8 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage IV (Distinguished Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 3 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
        'Master Teacher V' => [
            'education'   => 'Master’s degree in Education or Educational Leadership, or Educational Management, or relevant subject learning area',
            'training'    => '24 hours of relevant training in any cumulative of the following: Curriculum, pedagogy, Subject Specialization and 16 hours of training in Instructional Supervision acquired within 5 years or Completion of NEAP-requisite professional development program for Career Stage III (Distinguished Teacher)',
            'training_hours' => 24,
            'experience'  => '5 years of teaching experience and 4 years relevant experience in instructional supervision and technical assistance to teachers',
            'experience_years' => 5,
            'eligibility' => 'LET / RA 1080; or PBET / appropriate eligibility',
        ],
    ],

];
